/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeInfo;

import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Add_employee extends javax.swing.JFrame {

    String eid, ename, esnaem, eadd, econ, eage, epost, edep, ehdate, esalary, egen, eshift;
    private ImageIcon format = null;
    String filename = null;
    int s = 0;
    byte[] person_image = null;
    /**
     * Creates new form Employee
     *
     *
     */
    JFileChooser fc;
    File dir;
    File file = null;
    File f = new File("E:\\7. ADVANCE JAVA Sub-7\\Practic text file\\Employee Information\\Employee.txt");

    DefaultTableModel model;

    public Add_employee() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jsavedb = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTexEmId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTexage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTexsur = new javax.swing.JTextField();
        jTexconte = new javax.swing.JTextField();
        jTexfname = new javax.swing.JTextField();
        jTexaddress = new javax.swing.JTextField();
        jTexsalary = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jCombgender = new javax.swing.JComboBox<>();
        jCombdep = new javax.swing.JComboBox<>();
        jCombopost = new javax.swing.JComboBox<>();
        jComboshift = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jMenuItemprint = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuEdit_ = new javax.swing.JMenu();
        jMenuItemUpdate = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jMenuItemSechers = new javax.swing.JMenuItem();
        jMenulogin = new javax.swing.JMenu();
        jmanulogout = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        jLabel10.setText("jLabel10");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenuItem6.setText("jMenuItem6");

        jMenu13.setText("jMenu13");

        jMenu14.setText("jMenu14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0))));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(java.awt.Color.cyan);
        jLabel16.setText("mployee Management System");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 13));
        jLabel17.setText(" Easily Manage Your Employee Information");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_HP-Explorer-Dock-512_17242.png"))); // NOI18N

        jsavedb.setBackground(new java.awt.Color(0, 153, 153));
        jsavedb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jsavedb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_user-add_216490.png"))); // NOI18N
        jsavedb.setText("Add");
        jsavedb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsavedbActionPerformed(evt);
            }
        });

        jbtnclear.setBackground(new java.awt.Color(0, 153, 153));
        jbtnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_clean_.png"))); // NOI18N
        jbtnclear.setText("Cencel");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsavedb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jsavedb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel15.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel15.setText("Add New Employee");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "Employee Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Gender");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Shift");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Address");

        jTexEmId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("First Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Post");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Department");

        jTexage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Surname");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Contact");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Haire date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Age");

        jTexsur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTexconte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTexfname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTexaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTexsalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Basic Salary");

        jCombgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCombgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Male", "Female" }));

        jCombdep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCombdep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "HR", "Accounts", "Administrs", "Sales", "Purchase", "4th class", " ", " " }));

        jCombopost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCombopost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "General manager", "Assitent manager", "Finance manager", "Account manager", "Sales supervisor", "sales reprasentive" }));

        jComboshift.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboshift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Morning shift", "Day shift", "Night shift" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCombopost, javax.swing.GroupLayout.Alignment.LEADING, 0, 424, Short.MAX_VALUE)
                                .addComponent(jComboshift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTexage, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTexaddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                .addComponent(jTexconte, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jTexsur, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTexEmId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                .addComponent(jTexfname, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCombdep, javax.swing.GroupLayout.Alignment.LEADING, 0, 424, Short.MAX_VALUE)
                                .addComponent(jCombgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTexsalary)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTexEmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTexsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTexaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTexconte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTexage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCombgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCombdep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCombopost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboshift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTexsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 840, 500));

        jMenu1.setText("File");

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_Open.png"))); // NOI18N
        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpen);

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_save_46830.png"))); // NOI18N
        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSave);

        jMenuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_save_46830.png"))); // NOI18N
        jMenuItemSaveAs.setText("Save as");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSaveAs);

        jMenuItemprint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_Print_16x16.png"))); // NOI18N
        jMenuItemprint.setText("Print");
        jMenuItemprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemprintActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemprint);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_exit_3226.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu15.setText("Home");
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu15);

        jMenuEdit_.setText("Edit");

        jMenuItemUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_update_64935.png"))); // NOI18N
        jMenuItemUpdate.setText("Update Employee Info");
        jMenuItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateActionPerformed(evt);
            }
        });
        jMenuEdit_.add(jMenuItemUpdate);

        jMenuItemDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_DeleteRed.png"))); // NOI18N
        jMenuItemDelete.setText("Delete Employee Info");
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteActionPerformed(evt);
            }
        });
        jMenuEdit_.add(jMenuItemDelete);

        jMenuItemSechers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_system-search_.png"))); // NOI18N
        jMenuItemSechers.setText("Search Employee");
        jMenuItemSechers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSechersActionPerformed(evt);
            }
        });
        jMenuEdit_.add(jMenuItemSechers);

        jMenuBar1.add(jMenuEdit_);

        jMenulogin.setText("Login");
        jMenulogin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenuloginStateChanged(evt);
            }
        });
        jMenulogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuloginMouseClicked(evt);
            }
        });
        jMenulogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuloginActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenulogin);

        jmanulogout.setText("Logout");
        jmanulogout.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jmanulogoutStateChanged(evt);
            }
        });
        jmanulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmanulogoutMouseClicked(evt);
            }
        });
        jmanulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmanulogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmanulogout);

        jMenu8.setText("Help");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        jTexEmId.setText(null);
        jTexfname.setText(null);
        jTexsur.setText(null);
        jTexaddress.setText(null);
        jTexconte.setText(null);
        jTexage.setText(null);
        jTexsalary.setText(null);
        jCombgender.setSelectedItem("Select One");
        jCombdep.setSelectedItem("Select One");
        jCombopost.setSelectedItem("Select One");
        jComboshift.setSelectedItem("Select One");
        ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText(null);


    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jMenuItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUpdateActionPerformed

    private void jMenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDeleteActionPerformed

    private void jsavedbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsavedbActionPerformed
        // checkfild(); //check mathod null check.

        if (jTexEmId.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Type employee Id");
            jTexEmId.requestFocus();

        } else if (jTexfname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Name");
            jTexfname.requestFocus();

        } else if (jTexsur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Surname");
            jTexsur.requestFocus();

        } else if (jTexaddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Address");
            jTexaddress.requestFocus();

        } else if (jTexconte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Contact");
            jTexconte.requestFocus();

        } else if (jTexage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Age");
            jTexage.requestFocus();

        } else if (jTexsalary.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Salary");
            jTexsalary.requestFocus();

        }
        getAllrecord(); //getText mathod from field.
        Connection con = null;
        Statement stm = null;
        try {
            con = DBConnection.getDBConnection(); //class creeat for database connetion 
            stm = con.createStatement();
            int count = 0;
            count = stm.executeUpdate("insert into employee_info( EMP_id, EMP_F_name, EMP_Surname, EMP_Address, EMP_Contact, EMP_Age, EMP_Gender, EMP_Department, EMP_Post, EMP_Shift, EMP_H_date, EMP_B_salary,EMP_Image)values('" + eid + "','" + ename + "','" + esnaem + "','" + eadd + "','" + econ + "','" + eage + "','" + egen + "','" + edep + "','" + epost + "','" + eshift + "','" + ehdate + "','" + esalary + "','" + Arrays.toString(person_image) + "')");
            if (count > 0) {
                JOptionPane.showMessageDialog(this, "Successfully Save Data");
            } else {

                JOptionPane.showMessageDialog(this, " Save Faild");
            }
        } catch (HeadlessException | SQLException e) {
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException se) {
                System.out.println(se);
            }

        }

    }//GEN-LAST:event_jsavedbActionPerformed

    private void jMenuloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuloginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jMenuloginActionPerformed

    private void jmanulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmanulogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmanulogoutActionPerformed

    private void jmanulogoutStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jmanulogoutStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jmanulogoutStateChanged

    private void jMenuloginStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenuloginStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuloginStateChanged

    private void jMenuloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuloginMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jMenuloginMouseClicked

    private void jmanulogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmanulogoutMouseClicked
        // TODO add your handling code here:
        dispose();
        new LogIn().setVisible(true);

    }//GEN-LAST:event_jmanulogoutMouseClicked

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Are You sure Exits ?");
        System.exit(0); // for window close;
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemprintActionPerformed

    }//GEN-LAST:event_jMenuItemprintActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed

        checkfild();//check  null field  mathod.

        fc = new JFileChooser(dir);
        FileNameExtensionFilter filter;
        filter = new FileNameExtensionFilter("*.txt", new String[]{"txt"});
        fc.addChoosableFileFilter(filter);
        int option = fc.showSaveDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            dir = fc.getCurrentDirectory();
            file = fc.getSelectedFile();
            try {
                writeAll();//Write mathod for file chooser.
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed

        checkfild();           //check null field mathod.
        BufferedWriter bf = null;
        try {

            bf = new BufferedWriter(new FileWriter(f, true));
            bf.write(jTexEmId.getText() + ","
                    + jTexfname.getText() + ","
                    + jTexsur.getText() + ","
                    + jTexaddress.getText() + ","
                    + jTexconte.getText() + ","
                    + jTexage.getText() + ","
                    + jCombgender.getSelectedItem().toString() + ","
                    + jCombdep.getSelectedItem().toString() + ","
                    + jCombopost.getSelectedItem().toString() + ","
                    + jComboshift.getSelectedItem().toString() + ","
                    + ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText() + ","
                    + jTexsalary.getText()
            );
            JOptionPane.showMessageDialog(rootPane, "Save Successful");
            bf.newLine();

        } catch (HeadlessException | IOException e) {
        } finally {

            try {
                if (bf != null) {
                    bf.close();
                }
            } catch (IOException e) {
            }

        }
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        // save manu buttone
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
        // TODO add your handling code here:
        dispose();
          new Employee().setVisible(true);
    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenuItemSechersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSechersActionPerformed
        // TODO add your handling code here:
        this .dispose();
        new Search_employee().setVisible(true);
    }//GEN-LAST:event_jMenuItemSechersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Employee().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Add_employee().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCombdep;
    private javax.swing.JComboBox<String> jCombgender;
    private javax.swing.JComboBox<String> jCombopost;
    private javax.swing.JComboBox<String> jComboshift;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit_;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenuItem jMenuItemSechers;
    private javax.swing.JMenuItem jMenuItemUpdate;
    private javax.swing.JMenuItem jMenuItemprint;
    private javax.swing.JMenu jMenulogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTexEmId;
    private javax.swing.JTextField jTexaddress;
    private javax.swing.JTextField jTexage;
    private javax.swing.JTextField jTexconte;
    private javax.swing.JTextField jTexfname;
    private javax.swing.JTextField jTexsalary;
    private javax.swing.JTextField jTexsur;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JMenu jmanulogout;
    private javax.swing.JButton jsavedb;
    // End of variables declaration//GEN-END:variables

    private void getAllrecord() {

        eid = jTexEmId.getText();
        ename = jTexfname.getText();
        esnaem = jTexsur.getText();
        eadd = jTexaddress.getText();
        econ = jTexconte.getText();
        eage = jTexage.getText();
        egen = jCombgender.getSelectedItem().toString();
        edep = jCombdep.getSelectedItem().toString();
        epost = jCombopost.getSelectedItem().toString();
        eshift = jComboshift.getSelectedItem().toString();
        ehdate = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
        esalary = jTexsalary.getText();

    }

    private void writeAll() {
        BufferedWriter bf = null;

        try {

            bf = new BufferedWriter(new FileWriter(file + getExtention(), true));
            bf.write(jTexEmId.getText() + ","
                    + jTexfname.getText() + ","
                    + jTexsur.getText() + ","
                    + jTexaddress.getText() + ","
                    + jTexconte.getText() + ","
                    + jTexage.getText() + ","
                    + jCombgender.getSelectedItem().toString() + ","
                    + jCombdep.getSelectedItem().toString() + ","
                    + jCombopost.getSelectedItem().toString() + ","
                    + jComboshift.getSelectedItem().toString() + ","
                    + ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText() + ","
                    + jTexsalary.getText()
            );
            JOptionPane.showMessageDialog(rootPane, "Save Successful");
            bf.newLine();

        } catch (HeadlessException | IOException e) {
        } finally {

            try {
                if (bf != null) {
                    bf.close();
                }
            } catch (IOException e) {
            }

        }

    }

    private void checkfild() {

        if (jTexEmId.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Type employee Id");
            jTexEmId.requestFocus();

        } else if (jTexfname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Name");
            jTexfname.requestFocus();

        } else if (jTexsur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Surname");
            jTexsur.requestFocus();

        } else if (jTexaddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Address");
            jTexaddress.requestFocus();

        } else if (jTexconte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Contact");
            jTexconte.requestFocus();

        } else if (jTexage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Age");
            jTexage.requestFocus();

        } else if (jTexsalary.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Salary");
            jTexsalary.requestFocus();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Plese Attach an Image");

        }

    }

    private String getExtention() {
        String ext = "";
        String extension = fc.getFileFilter().getDescription();
        if (extension.equals("*.txt")) {
            ext = ".txt";

        }
        return ext;
    }

}
