/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeInfo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class Card_IN extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String time, a, b, c, d, e, dat, month, year;

    public Card_IN() {
        initComponents();
        date();
        time();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jleble_time = new javax.swing.JLabel();
        jLabDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnCardIn = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCombMonth = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Card In");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 18, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 30, -1, -1));

        jleble_time.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jleble_time.setForeground(new java.awt.Color(51, 255, 255));
        jleble_time.setText("Time");
        jPanel1.add(jleble_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 46, 168, -1));

        jLabDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabDate.setForeground(new java.awt.Color(0, 255, 255));
        jLabDate.setText("Date");
        jPanel1.add(jLabDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 18, 168, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Shift");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 195, -1, 20));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 194, 150, -1));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 153, 150, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Post");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 156, -1, -1));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setToolTipText("");
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 112, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Department");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 115, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 77, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 71, 150, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 30, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Employee ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 33, -1, -1));

        jBtnCardIn.setBackground(new java.awt.Color(0, 153, 153));
        jBtnCardIn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBtnCardIn.setText("CardIn");
        jBtnCardIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCardInActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnCardIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 140, -1));

        jBtnReset.setBackground(new java.awt.Color(0, 153, 153));
        jBtnReset.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Month");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Year");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 20));

        jCombMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCombMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "Fabruary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel2.add(jCombMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 140, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 470, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Employee().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBtnCardInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCardInActionPerformed
        // TODO add your handling code here:
        time = jleble_time.getText();
        a = jTextField1.getText();
        b = jTextField2.getText();
        c = jTextField3.getText();
        d = jTextField4.getText();
        e = jTextField5.getText();
        dat = jLabDate.getText();
        month = jCombMonth.getSelectedItem().toString();
        year = jTextField6.getText();

        Connection con = null;
        Statement stm = null;
        ResultSet rs1 = null;
        if (a.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Plese type Employee ID");
            jTextField1.requestFocus();

        } else if (b.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Plese type a valid employee ID");
            jTextField1.setText(null);
            jTextField1.requestFocus();
        } else {
            try {
                con = DBConnection.getDBConnection();
                stm = con.createStatement();

                rs1 = stm.executeQuery("select IN_TIME from emp_attendence where   EMP_ID = '"+a+"'and ATT_DATE ='" + dat + "'");

                if (rs1.next()) {
                    JOptionPane.showMessageDialog(rootPane, "Employee Already Card In");
                    jTextField1.setText(null);
                    jTextField2.setText(null);
                    jTextField3.setText(null);
                    jTextField4.setText(null);
                    jTextField5.setText(null);
                    jTextField6.setText(null);
                    jCombMonth.setSelectedItem("Select Month");
                    jTextField1.requestFocus();
                } else {

                    try {

                        stm = con.createStatement();
                        int count = 0;
                        count = stm.executeUpdate("insert into emp_attendence( EMP_ID, EMP_NAME, EMP_DEP, EMP_POST, EMP_SHIFT, ATT_DATE, IN_TIME, AT_MONTH, AT_YEAR)values('" + a + "','" + b + "','" + c + "','" + d + "','" + e + "','" + dat + "','" + time + "','" + month + "','" + year + "')");
                        if (count > 0) {
                            JOptionPane.showMessageDialog(rootPane, " Succecfully Card In ");
                            jTextField1.setText(null);
                            jTextField2.setText(null);
                            jTextField3.setText(null);
                            jTextField4.setText(null);
                            jTextField5.setText(null);
                            jTextField6.setText(null);
                            jCombMonth.setSelectedItem("Select Month");
                            jTextField1.requestFocus();

                        }

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                    } finally {
                        try {
                            con.close();
                            stm.close();
                        } catch (SQLException se) {
                            JOptionPane.showMessageDialog(rootPane, se);

                        }
                    }

                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    con.close();
                    stm.close();

                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(rootPane, se);
                }

            }
        }
    }//GEN-LAST:event_jBtnCardInActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String time = jleble_time.getText();
        String id = jTextField1.getText();

        String date = jLabDate.getText();
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;

        try {

            con = DBConnection.getDBConnection();

            stm = con.createStatement();
            rs = stm.executeQuery("select EMP_F_name,EMP_Department,EMP_Post,EMP_Shift from employee_info where EMP_id='" + id + "'");
            while (rs.next()) {
                jTextField2.setText(rs.getString("EMP_F_name"));
                jTextField3.setText(rs.getString("EMP_Department"));
                jTextField4.setText(rs.getString("EMP_Post"));
                jTextField5.setText(rs.getString("EMP_Shift"));

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
                rs.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }

        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jCombMonth.setSelectedItem("Select Month");
        jTextField1.requestFocus();


    }//GEN-LAST:event_jBtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Card_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Card_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Card_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Card_IN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Card_IN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCardIn;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCombMonth;
    private javax.swing.JLabel jLabDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel jleble_time;
    // End of variables declaration//GEN-END:variables

    public void date() {
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        jLabDate.setText(s.format(date));

    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                jleble_time.setText(s.format(date));

            }
        }).start();

    }

}
