/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeInfo;

import com.sun.xml.internal.ws.api.message.Message;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.nio.Buffer;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javafx.stage.FileChooser;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Employee extends javax.swing.JFrame {

    String eid, ename, esnaem, eadd, econ, eage, epost, edep, ehdate, esalary, egen, eshift;
    private ImageIcon format = null;
    String filename = null;
    int s = 0;
    byte[] person_image = null;
    /**
     * Creates new form Employee
     *
     *
     */
    JFileChooser fc;
    File dir;
    File file = null;
    File f = new File("E:\\7. ADVANCE JAVA Sub-7\\Practic text file\\Employee Information\\Employee.txt");

    DefaultTableModel model;

    public Employee() {
        initComponents();
        date();
        time();
        model = new DefaultTableModel();
        JEmptable.setModel(model);
        model.addColumn("EMP_NO");
        model.addColumn("EMP_id");
        model.addColumn("EMP_F_name");
        model.addColumn("EMP_Surname");
        model.addColumn("EMP_Address");
        model.addColumn("EMP_Contact");
        model.addColumn("EMP_Age");
        model.addColumn("EMP_Gender");
        model.addColumn("EMP_Department");
        model.addColumn("EMP_Post");
        model.addColumn("EMP_Shift");
        model.addColumn("EMP_H_date");
        model.addColumn("EMP_B_salary");
        model.addColumn("EMP_Image");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTexEmId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTexage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTexsur = new javax.swing.JTextField();
        jTexconte = new javax.swing.JTextField();
        jTexfname = new javax.swing.JTextField();
        jTexaddress = new javax.swing.JTextField();
        jTexsalary = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jCombgender = new javax.swing.JComboBox<>();
        jCombdep = new javax.swing.JComboBox<>();
        jCombopost = new javax.swing.JComboBox<>();
        jComboshift = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jupdate = new javax.swing.JButton();
        jbtnprint = new javax.swing.JButton();
        jbtnshow = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jbtndelete = new javax.swing.JButton();
        jsavedb = new javax.swing.JButton();
        jbtnlogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JEmptable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTexsearch = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabdate = new javax.swing.JLabel();
        jLabtime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jMenuItemprint = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuEdit_ = new javax.swing.JMenu();
        jMenuItemAdd_ = new javax.swing.JMenuItem();
        jMenuItemUpdate = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jMenuItemSechers = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuIteMonthSal = new javax.swing.JMenuItem();
        jMenuItemWeeklySel = new javax.swing.JMenuItem();
        jMenuItemPament = new javax.swing.JMenuItem();
        jMenulogin = new javax.swing.JMenu();
        jmanulogout = new javax.swing.JMenu();
        jmanuprint_ = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        jLabel10.setText("jLabel10");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenuItem6.setText("jMenuItem6");

        jMenu13.setText("jMenu13");

        jMenu14.setText("jMenu14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "Employee Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Gender");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Shift");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Address");

        jTexEmId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("First Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Post");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Employee ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Department");

        jTexage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Surname");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Contact");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Haire date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Age");

        jTexsur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTexconte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTexfname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTexaddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTexsalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Basic Salary");

        jCombgender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCombgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Male", "Female" }));

        jCombdep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCombdep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "HR", "Accounts", "Administrs", "Sales", "Purchase", "4th class", " ", " " }));

        jCombopost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCombopost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "General manager", "Assitent manager", "Finance manager", "Account manager", "Sales supervisor", "sales reprasentive" }));

        jComboshift.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboshift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Morning shift", "Day shift", "Night shift" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCombdep, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTexaddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTexconte, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTexage, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTexfname)
                                    .addComponent(jTexsur)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTexEmId)
                                            .addComponent(jCombgender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCombopost, 0, 162, Short.MAX_VALUE)
                                            .addComponent(jComboshift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTexsalary)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTexEmId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTexfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTexsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTexaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTexconte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTexage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCombgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCombdep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jCombopost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboshift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTexsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 290, 480));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "Oparations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        jupdate.setBackground(new java.awt.Color(0, 153, 153));
        jupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_update_64935.png"))); // NOI18N
        jupdate.setText("Update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jbtnprint.setBackground(new java.awt.Color(0, 153, 153));
        jbtnprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_Print_16x16.png"))); // NOI18N
        jbtnprint.setText("Print");
        jbtnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnprintActionPerformed(evt);
            }
        });

        jbtnshow.setBackground(new java.awt.Color(0, 153, 153));
        jbtnshow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_00-ELASTOFONT-STORE-READY_eye_2738306.png"))); // NOI18N
        jbtnshow.setText("Show");
        jbtnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnshowActionPerformed(evt);
            }
        });

        jbtnclear.setBackground(new java.awt.Color(0, 153, 153));
        jbtnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_clean_.png"))); // NOI18N
        jbtnclear.setText("Clear");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jbtndelete.setBackground(new java.awt.Color(0, 153, 153));
        jbtndelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_DeleteRed.png"))); // NOI18N
        jbtndelete.setText("Delete");
        jbtndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeleteActionPerformed(evt);
            }
        });

        jsavedb.setBackground(new java.awt.Color(0, 153, 153));
        jsavedb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jsavedb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_save_46830.png"))); // NOI18N
        jsavedb.setText("Save");
        jsavedb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsavedbActionPerformed(evt);
            }
        });

        jbtnlogout.setBackground(new java.awt.Color(0, 153, 153));
        jbtnlogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_gnome-session-logout_28390.png"))); // NOI18N
        jbtnlogout.setText("LogOut");
        jbtnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnlogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnshow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtndelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jsavedb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsavedb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnshow, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 170, 180, 480));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3), "Information Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        JEmptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JEmptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JEmptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JEmptable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 830, 480));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0))));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(java.awt.Color.cyan);
        jLabel16.setText("mployee Management System");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 13));
        jLabel17.setText(" Easily Manage Your Employee Information");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_HP-Explorer-Dock-512_17242.png"))); // NOI18N

        jTexsearch.setBackground(new java.awt.Color(204, 204, 255));
        jTexsearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTexsearch.setSelectionEnd(67);
        jTexsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexsearchActionPerformed(evt);
            }
        });
        jTexsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexsearchKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 255));
        jLabel14.setText("Search by Employee Name");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_system-search_.png"))); // NOI18N
        jLabel18.setText("Search");
        jLabel18.setToolTipText("Search");

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Total Employee");

        jLabdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabdate.setForeground(new java.awt.Color(255, 255, 255));
        jLabdate.setText("Date");

        jLabtime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabtime.setForeground(new java.awt.Color(255, 255, 255));
        jLabtime.setText("Time");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jLabel18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTexsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabtime, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabtime))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTexsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabdate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 160));

        jMenu1.setText("File");

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_save_46830.png"))); // NOI18N
        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSave);

        jMenuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSaveAs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_save_46830.png"))); // NOI18N
        jMenuItemSaveAs.setText("Save as");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSaveAs);

        jMenuItemprint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_Print_16x16.png"))); // NOI18N
        jMenuItemprint.setText("Print");
        jMenuItemprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemprintActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemprint);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_exit_3226.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu15.setText("Home");
        jMenuBar1.add(jMenu15);

        jMenuEdit_.setText("Edit");
        jMenuEdit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdit_ActionPerformed(evt);
            }
        });

        jMenuItemAdd_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_slice413_2859066.png"))); // NOI18N
        jMenuItemAdd_.setText("Add Employee");
        jMenuItemAdd_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdd_ActionPerformed(evt);
            }
        });
        jMenuEdit_.add(jMenuItemAdd_);

        jMenuItemUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_update_64935.png"))); // NOI18N
        jMenuItemUpdate.setText("Update Employee Info");
        jMenuItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateActionPerformed(evt);
            }
        });
        jMenuEdit_.add(jMenuItemUpdate);

        jMenuItemDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_DeleteRed.png"))); // NOI18N
        jMenuItemDelete.setText("Delete Employee Info");
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteActionPerformed(evt);
            }
        });
        jMenuEdit_.add(jMenuItemDelete);

        jMenuItemSechers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_system-search_.png"))); // NOI18N
        jMenuItemSechers.setText("Search Employee");
        jMenuItemSechers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSechersActionPerformed(evt);
            }
        });
        jMenuEdit_.add(jMenuItemSechers);

        jMenuBar1.add(jMenuEdit_);

        jMenu2.setText("Payroll");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu6.setText("Attendence");

        jMenuItem1.setText("Card In");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setText("Card Out");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem3.setText("Presented Employees");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenu2.add(jMenu6);

        jMenuIteMonthSal.setText("Monthly Salary");
        jMenuIteMonthSal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuIteMonthSalMouseClicked(evt);
            }
        });
        jMenuIteMonthSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIteMonthSalActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuIteMonthSal);

        jMenuItemWeeklySel.setText("Weekly Salary");
        jMenuItemWeeklySel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWeeklySelActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemWeeklySel);

        jMenuItemPament.setText("Paid Salary ");
        jMenuItemPament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPamentActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemPament);

        jMenuBar1.add(jMenu2);

        jMenulogin.setText("Login");
        jMenulogin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenuloginStateChanged(evt);
            }
        });
        jMenulogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuloginMouseClicked(evt);
            }
        });
        jMenulogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuloginActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenulogin);

        jmanulogout.setText("Logout");
        jmanulogout.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jmanulogoutStateChanged(evt);
            }
        });
        jmanulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmanulogoutMouseClicked(evt);
            }
        });
        jmanulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmanulogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmanulogout);

        jmanuprint_.setText("Print");
        jmanuprint_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmanuprint_MouseClicked(evt);
            }
        });
        jmanuprint_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmanuprint_ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmanuprint_);

        jMenu8.setText("Help");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        // field clear
        jTexEmId.setText(null);
        jTexfname.setText(null);
        jTexsur.setText(null);
        jTexaddress.setText(null);
        jTexconte.setText(null);
        jTexage.setText(null);
        jTexsalary.setText(null);
        jCombgender.setSelectedItem("Select One");
        jCombdep.setSelectedItem("Select One");
        jCombopost.setSelectedItem("Select One");
        jComboshift.setSelectedItem("Select One");
        ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText(null);

        // Table clear
        if (JEmptable.getRowCount() > 0) {
            for (int i = JEmptable.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        int row = JEmptable.getRowCount();
        String a = String.valueOf(row);
        jtxtTotal.setText(a);

    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdateActionPerformed
//        Update
        String update = jTexEmId.getText();

        Connection con = null;
        Statement pst = null;

        int count = 0;

        try {

            eid = jTexEmId.getText();
            ename = jTexfname.getText();
            esnaem = jTexsur.getText();
            eadd = jTexaddress.getText();
            econ = jTexconte.getText();
            eage = jTexage.getText();
            egen = jCombgender.getSelectedItem().toString();
            edep = jCombdep.getSelectedItem().toString();
            epost = jCombopost.getSelectedItem().toString();
            eshift = jComboshift.getSelectedItem().toString();
            ehdate = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
            esalary = jTexsalary.getText();

            con = DBConnection.getDBConnection();
            String sql = "update employee_info set EMP_id='" + eid + "',EMP_F_name='" + ename + "',EMP_Surname='" + esnaem + "',EMP_Address='" + eadd + "',"
                    + "EMP_Contact='" + econ + "',EMP_Age='" + eage + "',EMP_Gender='" + egen + "',EMP_Department='" + edep + "',EMP_Post='" + epost + "',EMP_Shift='" + eshift + "',EMP_H_date='" + ehdate + "',EMP_B_salary='" + esalary + "'where EMP_id='" + update + "'";
            pst = con.createStatement();
            count = pst.executeUpdate(sql);
            if (count > 0) {
                JOptionPane.showMessageDialog(null, "update successful");

            } else {

                JOptionPane.showMessageDialog(null, "update faild");

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error");

        }
    }//GEN-LAST:event_jupdateActionPerformed

    private void jbtndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeleteActionPerformed
        // TODO add your handling code here:

        if (JEmptable.getSelectedRow() >= 1) {
            String delete = jTexEmId.getText();
            int p = JOptionPane.showConfirmDialog(null, "Are you sure ", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
            Connection con = null;
            Statement stm = null;

            if (p == 0) {
                String sql = "delete from employee_info where EMP_id ='" + delete + "'";
                try {
                    con = DBConnection.getDBConnection();

                    stm = con.prepareStatement(sql);
                    stm.execute(sql);
                    JOptionPane.showMessageDialog(rootPane, "Delete Successful");
                    clear();

                    if (JEmptable.getRowCount() > 0) {
                        for (int i = JEmptable.getRowCount() - 1; i > -1; i--) {
                            model.removeRow(i);
                        }
                    }
                    int row = JEmptable.getRowCount();
                    String a = String.valueOf(row);
                    jtxtTotal.setText(a);
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        con.close();
                        stm.close();
                    } catch (SQLException se) {
                        System.out.println(se);
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "There ara no row selected");
        }
    }//GEN-LAST:event_jbtndeleteActionPerformed

    private void jbtnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("0");
        try {
            JEmptable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Can not Print%s%n ", e.getMessage());

        }
    }//GEN-LAST:event_jbtnprintActionPerformed

    private void jbtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jbtnlogoutActionPerformed

    private void jTexsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexsearchActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTexsearchActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed

        checkfild();           //check null field mathod.
        BufferedWriter bf = null;
        try {

            bf = new BufferedWriter(new FileWriter(f, true));
            bf.write(jTexEmId.getText() + ","
                    + jTexfname.getText() + ","
                    + jTexsur.getText() + ","
                    + jTexaddress.getText() + ","
                    + jTexconte.getText() + ","
                    + jTexage.getText() + ","
                    + jCombgender.getSelectedItem().toString() + ","
                    + jCombdep.getSelectedItem().toString() + ","
                    + jCombopost.getSelectedItem().toString() + ","
                    + jComboshift.getSelectedItem().toString() + ","
                    + ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText() + ","
                    + jTexsalary.getText()
            );
            JOptionPane.showMessageDialog(rootPane, "Save Successful");
            bf.newLine();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {

            try {
                if (bf != null) {
                    bf.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Are You sure Exits ?");
        System.exit(0); // for window close;
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUpdateActionPerformed

    private void jMenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteActionPerformed

        // TODO add your handling code here:
        if (JEmptable.getSelectedRow() >= 1) {
            String delete = jTexEmId.getText();
            int p = JOptionPane.showConfirmDialog(null, "Are you sure ", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
            Connection con = null;
            Statement stm = null;

            if (p == 0) {
                String sql = "delete from employee_info where EMP_id ='" + delete + "'";
                try {
                    con = DBConnection.getDBConnection();

                    stm = con.prepareStatement(sql);
                    stm.execute(sql);
                    JOptionPane.showMessageDialog(rootPane, "Delete Successful");
                    clear();

                    if (JEmptable.getRowCount() > 0) {
                        for (int i = JEmptable.getRowCount() - 1; i > -1; i--) {
                            model.removeRow(i);
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        con.close();
                        stm.close();
                    } catch (SQLException se) {
                        System.out.println(se);
                    }
                }
            }
        } else {

            JOptionPane.showMessageDialog(rootPane, "Thare are no row selected");

        }

    }//GEN-LAST:event_jMenuItemDeleteActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed

        checkfild();//check  null field  mathod.

        fc = new JFileChooser(dir);
        FileNameExtensionFilter filter;
        filter = new FileNameExtensionFilter("*.txt", new String[]{"txt"});
        fc.addChoosableFileFilter(filter);
        int option = fc.showSaveDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            dir = fc.getCurrentDirectory();
            file = fc.getSelectedFile();
            try {
                writeAll();//Write mathod for file chooser.
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jsavedbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsavedbActionPerformed
        // checkfild(); //check mathod null check.

        if (jTexEmId.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Type employee Id");
            jTexEmId.requestFocus();

        } else if (jTexfname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Name");
            jTexfname.requestFocus();

        } else if (jTexsur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Surname");
            jTexsur.requestFocus();

        } else if (jTexaddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Address");
            jTexaddress.requestFocus();

        } else if (jTexconte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Contact");
            jTexconte.requestFocus();

        } else if (jTexage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Age");
            jTexage.requestFocus();

        } else if (jTexsalary.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Salary");
            jTexsalary.requestFocus();

        }
        getAllrecord(); //getText mathod from field.
        Connection con = null;
        Statement stm = null;
        try {
            con = DBConnection.getDBConnection(); //class creeat for database connetion 
            stm = con.createStatement();
            int count = 0;
            count = stm.executeUpdate("insert into employee_info( EMP_id, EMP_F_name, EMP_Surname, EMP_Address, EMP_Contact, EMP_Age, EMP_Gender, EMP_Department, EMP_Post, EMP_Shift, EMP_H_date, EMP_B_salary,EMP_Image)values('" + eid + "','" + ename + "','" + esnaem + "','" + eadd + "','" + econ + "','" + eage + "','" + egen + "','" + edep + "','" + epost + "','" + eshift + "','" + ehdate + "','" + esalary + "','" + person_image + "')");
            if (count > 0) {
                JOptionPane.showMessageDialog(this, "Successfully Save Data");
            } else {

                JOptionPane.showMessageDialog(this, " Save Faild");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException se) {
                System.out.println(se);
            }

        }

    }//GEN-LAST:event_jsavedbActionPerformed

    private void jbtnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnshowActionPerformed
        displayInTable();
        // mathod for display data to table.
        int row = JEmptable.getRowCount();
        String a = String.valueOf(row);
        jtxtTotal.setText(a);

    }//GEN-LAST:event_jbtnshowActionPerformed

    private void JEmptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JEmptableMouseClicked
        int row = JEmptable.getSelectedRow();

        try {

            jTexEmId.setText(JEmptable.getValueAt(row, 1).toString());
            jTexfname.setText(JEmptable.getValueAt(row, 2).toString());
            jTexsur.setText(JEmptable.getValueAt(row, 3).toString());
            jTexaddress.setText(JEmptable.getValueAt(row, 4).toString());
            jTexconte.setText(JEmptable.getValueAt(row, 5).toString());
            jTexage.setText(JEmptable.getValueAt(row, 6).toString());

            jCombgender.setSelectedItem(JEmptable.getValueAt(row, 7).toString());
            jCombdep.setSelectedItem(JEmptable.getValueAt(row, 8).toString());
            jCombopost.setSelectedItem(JEmptable.getValueAt(row, 9).toString());
            jComboshift.setSelectedItem(JEmptable.getValueAt(row, 10).toString());

            ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText(JEmptable.getValueAt(row, 11).toString());
            jTexsalary.setText(JEmptable.getValueAt(row, 12).toString());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_JEmptableMouseClicked

    private void jMenuItemAdd_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdd_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Add_employee().setVisible(true);
    }//GEN-LAST:event_jMenuItemAdd_ActionPerformed

    private void jMenuloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuloginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jMenuloginActionPerformed

    private void jMenuItemprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("0");
        try {
            JEmptable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Can not Print%s%n ", e.getMessage());

        }

    }//GEN-LAST:event_jMenuItemprintActionPerformed

    private void jmanuprint_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmanuprint_ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("0");
        try {
            JEmptable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Can not Print%s%n ", e.getMessage());

        }
    }//GEN-LAST:event_jmanuprint_ActionPerformed

    private void jmanulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmanulogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmanulogoutActionPerformed

    private void jmanulogoutStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jmanulogoutStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jmanulogoutStateChanged

    private void jMenuloginStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenuloginStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuloginStateChanged

    private void jMenuloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuloginMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jMenuloginMouseClicked

    private void jmanulogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmanulogoutMouseClicked
        // TODO add your handling code here:
        dispose();
        new LogIn().setVisible(true);

    }//GEN-LAST:event_jmanulogoutMouseClicked

    private void jmanuprint_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmanuprint_MouseClicked
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("0");
        try {
            JEmptable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Can not Print%s%n ", e.getMessage());

        }
    }//GEN-LAST:event_jmanuprint_MouseClicked

    private void jMenuItemSechersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSechersActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Search_employee().setVisible(true);
    }//GEN-LAST:event_jMenuItemSechersActionPerformed

    private void jTexsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexsearchKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_jTexsearchKeyTyped

    private void jTexsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexsearchKeyReleased
        // TODO add your handling code here:
        String search = jTexsearch.getText();
        if (JEmptable.getRowCount() > 0) {
            for (int i = JEmptable.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            con = DBConnection.getDBConnection();
            //Create the Statement object
            stmt = con.createStatement();

            //Execute the query
            rs = stmt.executeQuery("select * from Employee_Info where EMP_F_name='" + search + "'");

            while (rs.next()) {

                model.addRow(new Object[]{rs.getString("EMP_NO"), rs.getString("EMP_id"), rs.getString("EMP_F_name"),
                    rs.getString("EMP_Surname"), rs.getString("EMP_Address"), rs.getString("EMP_Contact"),
                    rs.getString("EMP_Age"), rs.getString("EMP_Gender"), rs.getString("EMP_Department"),
                    rs.getString("EMP_Post"), rs.getString("EMP_Shift"), rs.getString("EMP_H_date"), rs.getString("EMP_B_salary"), rs.getString("EMP_Image")});

            }
            int row = JEmptable.getRowCount();
            String a = String.valueOf(row);
            jtxtTotal.setText(a);

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Close the connection and statement object
                con.close();
                stmt.close();
            } catch (SQLException ex) {
                System.out.println(ex);

            }
        }
    }//GEN-LAST:event_jTexsearchKeyReleased

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jMenuEdit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdit_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEdit_ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItemWeeklySelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWeeklySelActionPerformed
        // TODO add your handling code here:v
        dispose();
        new WeeklyWages().setVisible(true);
    }//GEN-LAST:event_jMenuItemWeeklySelActionPerformed

    private void jMenuIteMonthSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIteMonthSalActionPerformed
        // TODO add your handling code here: 
        this.dispose();
        new MonthlySalary().setVisible(true);
       
    }//GEN-LAST:event_jMenuIteMonthSalActionPerformed

    private void jMenuIteMonthSalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuIteMonthSalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuIteMonthSalMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Card_OUT().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new PresntEmployee().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Card_IN().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemPamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPamentActionPerformed
        // TODO add your handling code here
        this .dispose();
                        new PaySlip().setVisible(true);
    }//GEN-LAST:event_jMenuItemPamentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JEmptable;
    private javax.swing.JComboBox<String> jCombdep;
    private javax.swing.JComboBox<String> jCombgender;
    private javax.swing.JComboBox<String> jCombopost;
    private javax.swing.JComboBox<String> jComboshift;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabtime;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit_;
    private javax.swing.JMenuItem jMenuIteMonthSal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemAdd_;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemPament;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenuItem jMenuItemSechers;
    private javax.swing.JMenuItem jMenuItemUpdate;
    private javax.swing.JMenuItem jMenuItemWeeklySel;
    private javax.swing.JMenuItem jMenuItemprint;
    private javax.swing.JMenu jMenulogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexEmId;
    private javax.swing.JTextField jTexaddress;
    private javax.swing.JTextField jTexage;
    private javax.swing.JTextField jTexconte;
    private javax.swing.JTextField jTexfname;
    private javax.swing.JTextField jTexsalary;
    private javax.swing.JTextField jTexsearch;
    private javax.swing.JTextField jTexsur;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtndelete;
    private javax.swing.JButton jbtnlogout;
    private javax.swing.JButton jbtnprint;
    private javax.swing.JButton jbtnshow;
    private javax.swing.JMenu jmanulogout;
    private javax.swing.JMenu jmanuprint_;
    private javax.swing.JButton jsavedb;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JButton jupdate;
    // End of variables declaration//GEN-END:variables

    private void getAllrecord() {

        eid = jTexEmId.getText();
        ename = jTexfname.getText();
        esnaem = jTexsur.getText();
        eadd = jTexaddress.getText();
        econ = jTexconte.getText();
        eage = jTexage.getText();
        egen = jCombgender.getSelectedItem().toString();
        edep = jCombdep.getSelectedItem().toString();
        epost = jCombopost.getSelectedItem().toString();
        eshift = jComboshift.getSelectedItem().toString();
        ehdate = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
        esalary = jTexsalary.getText();

    }

    private void writeAll() {
        BufferedWriter bf = null;

        try {

            bf = new BufferedWriter(new FileWriter(file + getExtention(), true));
            bf.write(jTexEmId.getText() + ","
                    + jTexfname.getText() + ","
                    + jTexsur.getText() + ","
                    + jTexaddress.getText() + ","
                    + jTexconte.getText() + ","
                    + jTexage.getText() + ","
                    + jCombgender.getSelectedItem().toString() + ","
                    + jCombdep.getSelectedItem().toString() + ","
                    + jCombopost.getSelectedItem().toString() + ","
                    + jComboshift.getSelectedItem().toString() + ","
                    + ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText() + ","
                    + jTexsalary.getText()
            );
            JOptionPane.showMessageDialog(rootPane, "Save Successful");
            bf.newLine();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {

            try {
                if (bf != null) {
                    bf.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }

    private void checkfild() {

        if (jTexEmId.getText().isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Type employee Id");
            jTexEmId.requestFocus();

        } else if (jTexfname.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Name");
            jTexfname.requestFocus();

        } else if (jTexsur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Surname");
            jTexsur.requestFocus();

        } else if (jTexaddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Address");
            jTexaddress.requestFocus();

        } else if (jTexconte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Contact");
            jTexconte.requestFocus();

        } else if (jTexage.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Age");
            jTexage.requestFocus();

        } else if (jTexsalary.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type employee Salary");
            jTexsalary.requestFocus();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Plese Attach an Image");

        }

    }

    private String getExtention() {
        String ext = "";
        String extension = fc.getFileFilter().getDescription();
        if (extension.equals("*.txt")) {
            ext = ".txt";

        }
        return ext;
    }

    public void displayInTable() {
        if (JEmptable.getRowCount() > 0) {
            for (int i = JEmptable.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            con = DBConnection.getDBConnection();
            //Create the Statement object
            stmt = con.createStatement();

            //Execute the query
            rs = stmt.executeQuery("select * from Employee_Info order by EMP_NO");

            while (rs.next()) {

                model.addRow(new Object[]{rs.getString("EMP_NO"), rs.getString("EMP_id"), rs.getString("EMP_F_name"),
                    rs.getString("EMP_Surname"), rs.getString("EMP_Address"), rs.getString("EMP_Contact"),
                    rs.getString("EMP_Age"), rs.getString("EMP_Gender"), rs.getString("EMP_Department"),
                    rs.getString("EMP_Post"), rs.getString("EMP_Shift"), rs.getString("EMP_H_date"), rs.getString("EMP_B_salary"), rs.getString("EMP_Image")});

            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Close the connection and statement object
                con.close();
                stmt.close();
            } catch (SQLException ex) {
                System.out.println(ex);

            }
        }
    }

    private void clear() {
        jTexEmId.setText(null);
        jTexfname.setText(null);
        jTexsur.setText(null);
        jTexaddress.setText(null);
        jTexconte.setText(null);
        jTexage.setText(null);
        jTexsalary.setText(null);
        jCombgender.setSelectedItem("Select One");
        jCombdep.setSelectedItem("Select One");
        jCombopost.setSelectedItem("Select One");
        jComboshift.setSelectedItem("Select One");
        ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).setText(null);

    }

    public void date() {
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        jLabdate.setText(s.format(date));

    }

    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                jLabtime.setText(s.format(date));

            }
        }).start();

    }
}
