/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeInfo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MonthlySalary extends javax.swing.JFrame {

    /**
     * Creates new form Payroll
     */
    public MonthlySalary() {
        initComponents();
        jTextOTDu.setText("0");
        jTextactual.setText("0");
        jTextabsence.setText("0");
        jTextE1.setText("0");
        jTextE8.setText("0");
        jTextD5.setText("0");
        jTextD6.setText("0");

    }
    String eid, ename, bsel, egross, net, mon, yer, pf, insfu, wlf, intx, advc, pos, dep ,ded;
    double basic;
    double b;
    double c;
    double d;
    double e;
    double f;
    double g;
    double h;
    double i;
    double j;
    double k;
    double l;
    double m;
    double n;
    double o;

    double hrA, dA, mA, pay, actual, atten;
    double proF, wF, inF, incomeT;
    double gross, deduc, bnetSal, anetsel;
    String id, month, year, shedule, at;
    int att = 0;
    int ov = 0;
    int ab = 0;
    int a = 0;
    int paysel = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextEmpsalary = new javax.swing.JTextField();
        jTextEmpname = new javax.swing.JTextField();
        jtxtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextE1 = new javax.swing.JTextField();
        jTextE2 = new javax.swing.JTextField();
        jTextE3 = new javax.swing.JTextField();
        jTextE4 = new javax.swing.JTextField();
        jTextE5 = new javax.swing.JTextField();
        jTextE6 = new javax.swing.JTextField();
        jTextE7 = new javax.swing.JTextField();
        jTextE8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextD1 = new javax.swing.JTextField();
        jTextD2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextD3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextD4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextD5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextD6 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jBtntotal = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextPost = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextOTDu = new javax.swing.JTextField();
        jCombMonth = new javax.swing.JComboBox<>();
        jTextYear = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jtextgross = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextDeduction = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextanetsel = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextshedule = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextactual = new javax.swing.JTextField();
        jLababsence = new javax.swing.JLabel();
        jTextabsence = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextpaysel = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTexdepartment = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Monthly Salary sheet");

        jButton3.setBackground(new java.awt.Color(0, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 496, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(537, 537, 537))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        jTextEmpsalary.setEditable(false);
        jTextEmpsalary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextEmpsalary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextEmpname.setEditable(false);
        jTextEmpname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtxtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdActionPerformed(evt);
            }
        });
        jtxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtIdKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Basic Salary");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Employee Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Employee ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Deductions");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Overtime Wages (TK)");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setAlignmentY(0.0F);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Dearness Allowance (% of Basic salary )");
        jLabel8.setAlignmentX(0.5F);
        jLabel8.setAlignmentY(0.0F);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Madical Allowance (% of Basic salary)");
        jLabel9.setAlignmentX(0.5F);
        jLabel9.setAlignmentY(0.0F);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("House Rent Allowance (% of Basic salary)");
        jLabel10.setAlignmentX(0.5F);
        jLabel10.setAlignmentY(0.0F);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Conveynce Allowance (TK)");
        jLabel11.setToolTipText("");
        jLabel11.setAlignmentX(0.5F);
        jLabel11.setAlignmentY(0.0F);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Mobile Allowance (TK)");
        jLabel12.setAlignmentX(0.5F);
        jLabel12.setAlignmentY(0.0F);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tifin Allowance (TK)");
        jLabel13.setAlignmentX(0.5F);
        jLabel13.setAlignmentY(0.0F);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Othars Allowance (TK)");
        jLabel14.setAlignmentX(0.5F);
        jLabel14.setAlignmentY(0.0F);

        jTextE1.setEditable(false);
        jTextE1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextE1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextE2.setEditable(false);
        jTextE2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextE2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextE3.setEditable(false);
        jTextE3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextE3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextE4.setEditable(false);
        jTextE4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextE4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextE5.setEditable(false);
        jTextE5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextE5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextE6.setEditable(false);
        jTextE6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextE6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextE7.setEditable(false);
        jTextE7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextE7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextE7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextE7ActionPerformed(evt);
            }
        });

        jTextE8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextE8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Provident Fund (% of basic salary)");

        jTextD1.setEditable(false);
        jTextD1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextD1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextD2.setEditable(false);
        jTextD2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextD2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Welfare Fund (% of Basic salary)");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Insurance Premium of workers (% of Basic salary )");

        jTextD3.setEditable(false);
        jTextD3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextD3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Income Tax (% of Basic salary)");

        jTextD4.setEditable(false);
        jTextD4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextD4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Recovery of Advance (TK)");
        jLabel20.setToolTipText("");

        jTextD5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextD5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setText("Monthly Earnings");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Others Deduction (TK)");
        jLabel22.setToolTipText("");

        jTextD6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextD6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextD6ActionPerformed(evt);
            }
        });

        jBtntotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtntotal.setText("Total");
        jBtntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtntotalActionPerformed(evt);
            }
        });

        jbtnreset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });

        jbtnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtntotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnreset)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBtntotal)
                .addGap(18, 18, 18)
                .addComponent(jbtnreset)
                .addGap(18, 18, 18)
                .addComponent(jbtnSave)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Month");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Year");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Post");

        jTextPost.setEditable(false);
        jTextPost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Number of Overtime days");

        jTextOTDu.setEditable(false);
        jTextOTDu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextOTDu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextOTDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOTDuActionPerformed(evt);
            }
        });

        jCombMonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCombMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "Fabruary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jTextYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextYearKeyReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setText("Gross Salary");

        jtextgross.setEditable(false);
        jtextgross.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtextgross.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtextgross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextgrossActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 204));
        jLabel23.setText("Total deduction");

        jTextDeduction.setEditable(false);
        jTextDeduction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextDeduction.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextDeduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDeductionActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 204));
        jLabel29.setText("  Net salary");

        jTextanetsel.setEditable(false);
        jTextanetsel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextanetsel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(47, 47, 47)
                .addComponent(jtextgross, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jTextDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel29)
                .addGap(26, 26, 26)
                .addComponent(jTextanetsel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDeduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jtextgross, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel29)
                    .addComponent(jTextanetsel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Number of shedule dutys");

        jTextshedule.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextshedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextsheduleActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Number of actual dutys");

        jTextactual.setEditable(false);
        jTextactual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextactual.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextactualActionPerformed(evt);
            }
        });

        jLababsence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLababsence.setText("Nomber of absence days");

        jTextabsence.setEditable(false);
        jTextabsence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextabsence.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Pay salary (TK)");

        jTextpaysel.setEditable(false);
        jTextpaysel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextpaysel.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Department");

        jTexdepartment.setEditable(false);
        jTexdepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexdepartment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextactual)
                                    .addComponent(jTextshedule))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextEmpname, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLababsence))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextOTDu, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(jTextabsence)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextE4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jTextE5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextE6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextE7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextE8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextE1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextE2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextE3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextpaysel))))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextD4)
                            .addComponent(jTextD5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextD6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextD1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextD2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextD3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextEmpsalary)
                                    .addComponent(jTextPost)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(jTexdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCombMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextYear, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addGap(61, 61, 61)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(jCombMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextEmpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextOTDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30)
                        .addComponent(jLabel24)
                        .addComponent(jTextshedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextEmpsalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(jTextactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLababsence)
                        .addComponent(jTextabsence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextPost, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(jTextpaysel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextE4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextE5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jTextD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jTextD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextD5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextD6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTextE6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextE7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jTextE8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1350, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIdKeyReleased
        // TODO add your handling code here:
        String Id = jtxtId.getText();
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DBConnection.getDBConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select EMP_F_name,EMP_B_salary,EMP_Department,EMP_Post from employee_info where EMP_id='" + Id + "'");
            while (rs.next()) {
                jTextEmpname.setText(rs.getString("EMP_F_name"));
                jTexdepartment.setText(rs.getString("EMP_Department"));
                jTextEmpsalary.setText(rs.getString("EMP_B_salary"));
                jTextPost.setText(rs.getString("EMP_Post"));

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
                rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }

        }

        String post = jTextPost.getText();

        if ("General manager".equals(post)) {

            jTextE2.setText("40");
            jTextE3.setText("10");
            jTextE4.setText("10");
            jTextE5.setText("5000");
            jTextE6.setText("5000");
            jTextE7.setText("3000");
            jTextD1.setText("10");
            jTextD2.setText("10");
            jTextD3.setText("5");
            jTextD4.setText("15");
        } else if ("Assitent manager".equals(post)) {
            jTextE2.setText("40");
            jTextE3.setText("10");
            jTextE4.setText("5");
            jTextE5.setText("1500");
            jTextE6.setText("1000");
            jTextE7.setText("1000");
            jTextD1.setText("10");
            jTextD2.setText("10");
            jTextD3.setText("5");
            jTextD4.setText("15");
        } else if ("Finance manager".equals(post)) {
            jTextE2.setText("40");
            jTextE3.setText("10");
            jTextE4.setText("5");
            jTextE5.setText("2000");
            jTextE6.setText("1000");
            jTextE7.setText("1500");
            jTextD1.setText("10");
            jTextD2.setText("10");
            jTextD3.setText("5");
            jTextD4.setText("15");
        } else if ("Account manager".equals(post)) {
            jTextE2.setText("40");
            jTextE3.setText("10");
            jTextE4.setText("5");
            jTextE5.setText("2000");
            jTextE6.setText("1000");
            jTextE7.setText("1500");
            jTextD1.setText("10");
            jTextD2.setText("10");
            jTextD3.setText("5");
            jTextD4.setText("15");
        } else if ("Sales supervisor".equals(post)) {
            jTextE2.setText("40");
            jTextE3.setText("5");
            jTextE4.setText("5");
            jTextE5.setText("2000");
            jTextE6.setText("1000");
            jTextE7.setText("1000");
            jTextD1.setText("5");
            jTextD2.setText("5");
            jTextD3.setText("2");
            jTextD4.setText("15");
        } else if ("sales reprasentive".equals(post)) {
            jTextE2.setText("40");
            jTextE3.setText("5");
            jTextE4.setText("5");
            jTextE5.setText("2000");
            jTextE6.setText("1000");
            jTextE7.setText("1000");
            jTextD1.setText("5");
            jTextD2.setText("5");
            jTextD3.setText("2");
            jTextD4.setText("15");
        }
    }//GEN-LAST:event_jtxtIdKeyReleased

    private void jTextE7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextE7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextE7ActionPerformed

    private void jTextD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextD6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextD6ActionPerformed

    private void jBtntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtntotalActionPerformed
        if (jtxtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Plese Type Employee ID");

        } else {
            atten = Integer.valueOf(jTextshedule.getText());
            actual = Integer.valueOf(jTextactual.getText());
            basic = Integer.valueOf(jTextEmpsalary.getText());
            int ot = Integer.valueOf(jTextOTDu.getText());
            int overtimetk = (int) ((ot * 1.5 * basic) / 30);
            jTextE1.setText(String.valueOf(overtimetk));

            c = Integer.valueOf(jTextE2.getText());
            d = Integer.valueOf(jTextE3.getText());
            e = Integer.valueOf(jTextE4.getText());
            f = Integer.valueOf(jTextE5.getText());
            g = Integer.valueOf(jTextE6.getText());
            h = Integer.valueOf(jTextE7.getText());
            i = Integer.valueOf(jTextE8.getText());
            j = Integer.valueOf(jTextD1.getText());
            k = Integer.valueOf(jTextD2.getText());
            l = Integer.valueOf(jTextD3.getText());
            m = Integer.valueOf(jTextD4.getText());
            n = Integer.valueOf(jTextD5.getText());
            o = Integer.valueOf(jTextD6.getText());

            if (atten <= actual) {

                jTextpaysel.setText(String.valueOf(basic));
            } else if (atten > actual) {
                paysel = (int) ((basic * actual) / 30);

                jTextpaysel.setText(String.valueOf(paysel));
            }

            hrA = (basic * c) / 100;
            dA = (basic * d) / 100;
            mA = (basic * e) / 100;
            proF = (basic * j) / 100;
            wF = (basic * k) / 100;
            inF = (basic * l) / 100;
            incomeT = (basic * m) / 100;

            gross = paysel + overtimetk + hrA + dA + mA + f + g + h + i;
            deduc = proF + wF + inF + incomeT + n + o;
            bnetSal = gross - deduc;

            jtextgross.setText(String.valueOf(gross));
            jTextDeduction.setText(String.valueOf(deduc));

            jTextanetsel.setText(String.valueOf(bnetSal));
        }
    }//GEN-LAST:event_jBtntotalActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        //Reset All information

        jtxtId.setText(null);
        jTextOTDu.setText("0");
        jTextactual.setText("0");
        jTextabsence.setText("0");
        jTextshedule.setText(null);
        jTextYear.setText(null);
        jTextPost.setText(null);
        jTexdepartment.setText(null);
        jTextEmpname.setText(null);
        jTextEmpsalary.setText(null);
        jTextpaysel.setText(null);
        jTextEmpsalary.setText(null);

        jtextgross.setText(null);
        jTextDeduction.setText(null);
        jTextanetsel.setText(null);

        jCombMonth.setSelectedItem("Select Month");
        jTextE1.setText(null);
        jTextE2.setText(null);
        jTextE3.setText(null);
        jTextE4.setText(null);
        jTextD1.setText(null);
        jTextD2.setText(null);
        jTextD3.setText(null);
        jTextD4.setText(null);

        jTextE5.setText(null);
        jTextE6.setText(null);
        jTextE7.setText(null);
        jTextE8.setText("0");
        jTextD5.setText("0");
        jTextD6.setText("0");

    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Employee().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtxtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdActionPerformed

    private void jTextDeductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDeductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDeductionActionPerformed

    private void jtextgrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextgrossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextgrossActionPerformed

    private void jTextsheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextsheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextsheduleActionPerformed

    private void jTextYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextYearKeyReleased
        // TODO add your handling code here:
        shedule = jTextshedule.getText();
        month = jCombMonth.getSelectedItem().toString();
        if (shedule.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Plese type Nomver of  shedule dutys");
            jTextshedule.requestFocus();
        } else if (month.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Plese Select Month");
        } else {
            id = jtxtId.getText();
            month = jCombMonth.getSelectedItem().toString();
            year = jTextYear.getText();
            month = jCombMonth.getSelectedItem().toString();
            shedule = jTextshedule.getText();
            a = Integer.parseInt(shedule);

            basic = Integer.valueOf(jTextEmpsalary.getText());

            Connection con = null;
            Statement stm = null;
            ResultSet rs = null;
            try {
                con = DBConnection.getDBConnection();
                stm = con.createStatement();

                rs = stm.executeQuery("SELECT * FROM emp_attendence where EMP_ID='" + id + "' and AT_MONTH='" + month + "'and AT_YEAR='" + year + "'");

                while (rs.next()) {
                    att = rs.getRow();
                    at = String.valueOf(att);
                    jTextactual.setText(at);
                }
                if (a > att) {

                    ov = a - att;
                    String ovr = String.valueOf(ov);
                    jTextOTDu.setText("0");
                    jTextabsence.setText(ovr);

                } else if (a < att) {
                    ab = att - a;
                    String abs = String.valueOf(ab);

                    jTextOTDu.setText(abs);
                    jTextabsence.setText("0");

                } else if (att == a) {

                    jTextOTDu.setText("0");
                    jTextabsence.setText("0");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "there are no racorde found ");

                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    con.close();
                    stm.close();
                    rs.close();
                } catch (SQLException se) {
                    JOptionPane.showMessageDialog(null, se);

                }

            }
        }

    }//GEN-LAST:event_jTextYearKeyReleased

    private void jTextactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextactualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextactualActionPerformed

    private void jTextOTDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOTDuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOTDuActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
        //  Emp_ID, Emp_name, B_Salary, Gross_salary, Net_Salary, Month, Year, Pro_Fund, Insu_Fund, Wel_Fund, In_Tax, Advence

        eid = jtxtId.getText();
        ename = jTextEmpname.getText();
        dep = jTexdepartment.getText();
        pos = jTextPost.getText();
        bsel = jTextEmpsalary.getText();
        egross = jtextgross.getText();
        ded = jTextDeduction.getText();
        net = jTextanetsel.getText();
        mon = jCombMonth.getSelectedItem().toString();
        yer = jTextYear.getText();
        pf = jTextD1.getText();
        insfu = jTextD3.getText();
        wlf = jTextD2.getText();
        intx = jTextD4.getText();
        advc = jTextD6.getText();
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DBConnection.getDBConnection();
            stm = con.createStatement();

            rs = stm.executeQuery("SELECT * FROM monthly_salary where Emp_ID='" + eid + "' and Sal_Month ='" + mon + "' and Sal_Year='" + yer + "'");

            if (rs.next()) {
                JOptionPane.showMessageDialog(rootPane, "Salary sheet hes been Already Created");

            } else {
                try {
                    con = DBConnection.getDBConnection();
                    stm = con.createStatement();
                    int count = 0;
                    count = stm.executeUpdate("insert into monthly_salary (  Emp_ID, Emp_name, Emp_dep, Emp_post, B_Salary, Gross_salary, Net_Salary, Sal_Month, Sal_Year, Pro_Fund, Insu_Fund, Wel_Fund, Advence, IncomTax, Deduction)values "
                            + "('" + eid + "','" + ename + "','" + dep + "','" + pos + "','" + bsel + "','" + egross + "','" + net + "','" + mon + "','" + yer + "','" + pf + "','" + insfu + "','" + wlf + "','" + advc + "','" + intx + "','" + ded + "')");
                    if (count > 0) {
                        JOptionPane.showMessageDialog(rootPane, "Salary Sheet Creation Complet");

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Salary creation failed");

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        con.close();
                        stm.close();
                    } catch (SQLException se) {
                        JOptionPane.showMessageDialog(null, se);

                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
                rs.close();
            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, se);
            }
        }


    }//GEN-LAST:event_jbtnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonthlySalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonthlySalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonthlySalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonthlySalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonthlySalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtntotal;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCombMonth;
    private javax.swing.JLabel jLababsence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTexdepartment;
    private javax.swing.JTextField jTextD1;
    private javax.swing.JTextField jTextD2;
    private javax.swing.JTextField jTextD3;
    private javax.swing.JTextField jTextD4;
    private javax.swing.JTextField jTextD5;
    private javax.swing.JTextField jTextD6;
    private javax.swing.JTextField jTextDeduction;
    private javax.swing.JTextField jTextE1;
    private javax.swing.JTextField jTextE2;
    private javax.swing.JTextField jTextE3;
    private javax.swing.JTextField jTextE4;
    private javax.swing.JTextField jTextE5;
    private javax.swing.JTextField jTextE6;
    private javax.swing.JTextField jTextE7;
    private javax.swing.JTextField jTextE8;
    private javax.swing.JTextField jTextEmpname;
    private javax.swing.JTextField jTextEmpsalary;
    private javax.swing.JTextField jTextOTDu;
    private javax.swing.JTextField jTextPost;
    private javax.swing.JTextField jTextYear;
    private javax.swing.JTextField jTextabsence;
    private javax.swing.JTextField jTextactual;
    private javax.swing.JTextField jTextanetsel;
    private javax.swing.JTextField jTextpaysel;
    private javax.swing.JTextField jTextshedule;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JTextField jtextgross;
    private javax.swing.JTextField jtxtId;
    // End of variables declaration//GEN-END:variables
}
