/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeInfo;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Search_employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     *
     *
     */
    DefaultTableModel model;

    public Search_employee() {
        initComponents();
        model = new DefaultTableModel();
        JEmptable.setModel(model);
        model.addColumn("EMP_NO");
        model.addColumn("EMP_id");
        model.addColumn("EMP_F_name");
        model.addColumn("EMP_Surname");
        model.addColumn("EMP_Address");
        model.addColumn("EMP_Contact");
        model.addColumn("EMP_Age");
        model.addColumn("EMP_Gender");
        model.addColumn("EMP_Department");
        model.addColumn("EMP_Post");
        model.addColumn("EMP_Shift");
        model.addColumn("EMP_H_date");
        model.addColumn("EMP_B_salary");
        model.addColumn("EMP_Image");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JEmptable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbtnclear = new javax.swing.JButton();
        jTexsearch = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemprint = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuEdit_ = new javax.swing.JMenu();
        jMenuItemAdd_ = new javax.swing.JMenuItem();
        jMenulogin = new javax.swing.JMenu();
        jmanulogout = new javax.swing.JMenu();
        jmanuprint_ = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        jLabel10.setText("jLabel10");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenuItem6.setText("jMenuItem6");

        jMenu13.setText("jMenu13");

        jMenu14.setText("jMenu14");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Information Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        JEmptable.setBackground(new java.awt.Color(0, 102, 102));
        JEmptable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JEmptable.setForeground(new java.awt.Color(255, 255, 255));
        JEmptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JEmptable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JEmptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JEmptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JEmptable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1330, 490));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0))));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(java.awt.Color.cyan);
        jLabel16.setText("mployee Management System");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 13));
        jLabel17.setText(" Easily Manage Your Employee Information");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_HP-Explorer-Dock-512_17242.png"))); // NOI18N

        jbtnclear.setBackground(new java.awt.Color(0, 153, 153));
        jbtnclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_clean_.png"))); // NOI18N
        jbtnclear.setText("Clear");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jTexsearch.setBackground(new java.awt.Color(204, 204, 255));
        jTexsearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTexsearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jTexsearch.setSelectionEnd(67);
        jTexsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexsearchActionPerformed(evt);
            }
        });
        jTexsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTexsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTexsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexsearchKeyTyped(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(153, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 204, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_system-search_.png"))); // NOI18N
        jLabel18.setText("Search");
        jLabel18.setToolTipText("Search");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 255));
        jLabel14.setText("Search by Employee Name");
        jLabel14.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel17)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTexsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnclear)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 140));

        jMenu1.setText("File");

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_Open.png"))); // NOI18N
        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpen);

        jMenuItemprint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_Print_16x16.png"))); // NOI18N
        jMenuItemprint.setText("Print");
        jMenuItemprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemprintActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemprint);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_exit_3226.png"))); // NOI18N
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu15.setText("Home");
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu15);

        jMenuEdit_.setText("Edit");
        jMenuEdit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEdit_ActionPerformed(evt);
            }
        });

        jMenuItemAdd_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeInfo/if_slice413_2859066.png"))); // NOI18N
        jMenuItemAdd_.setText("Add Employee");
        jMenuItemAdd_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdd_ActionPerformed(evt);
            }
        });
        jMenuEdit_.add(jMenuItemAdd_);

        jMenuBar1.add(jMenuEdit_);

        jMenulogin.setText("Login");
        jMenulogin.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenuloginStateChanged(evt);
            }
        });
        jMenulogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuloginMouseClicked(evt);
            }
        });
        jMenulogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuloginActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenulogin);

        jmanulogout.setText("Logout");
        jmanulogout.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jmanulogoutStateChanged(evt);
            }
        });
        jmanulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmanulogoutMouseClicked(evt);
            }
        });
        jmanulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmanulogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmanulogout);

        jmanuprint_.setText("Print");
        jmanuprint_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmanuprint_MouseClicked(evt);
            }
        });
        jmanuprint_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmanuprint_ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmanuprint_);

        jMenu8.setText("Help");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed

        if (JEmptable.getRowCount() > 0) {
            for (int i = JEmptable.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }


    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jTexsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexsearchActionPerformed

    private void JEmptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JEmptableMouseClicked


    }//GEN-LAST:event_JEmptableMouseClicked

    private void jMenuloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuloginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jMenuloginActionPerformed

    private void jmanuprint_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmanuprint_ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("0");
        try {
            JEmptable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Can not Print%s%n ", e.getMessage());

        }
    }//GEN-LAST:event_jmanuprint_ActionPerformed

    private void jmanulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmanulogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmanulogoutActionPerformed

    private void jmanulogoutStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jmanulogoutStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jmanulogoutStateChanged

    private void jMenuloginStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenuloginStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuloginStateChanged

    private void jMenuloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuloginMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jMenuloginMouseClicked

    private void jmanulogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmanulogoutMouseClicked
        // TODO add your handling code here:
        dispose();
        new LogIn().setVisible(true);

    }//GEN-LAST:event_jmanulogoutMouseClicked

    private void jmanuprint_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmanuprint_MouseClicked
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("0");
        try {
            JEmptable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Can not Print%s%n ", e.getMessage());

        }
    }//GEN-LAST:event_jmanuprint_MouseClicked

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Are You sure Exits ?");
        System.exit(0); // for window close;
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("0");
        try {
            JEmptable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Can not Print%s%n ", e.getMessage());

        }

    }//GEN-LAST:event_jMenuItemprintActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        // save manu buttone

    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jTexsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexsearchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexsearchKeyTyped

    private void jTexsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexsearchKeyReleased
        // TODO add your handling code here:
        String search = jTexsearch.getText();
        if (JEmptable.getRowCount() > 0) {
            for (int i = JEmptable.getRowCount() - 1; i > -1; i--) {
                model.removeRow(i);
            }
        }
        Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
     
        
        try {
            con = DBConnection.getDBConnection();
            //Create the Statement object
            stmt = con.createStatement();

            //Execute the query
            rs = stmt.executeQuery("select * from Employee_Info where EMP_Surname='" + search + "'");
       
            while (rs.next()) {

                model.addRow(new Object[]{rs.getString("EMP_NO"), rs.getString("EMP_id"), rs.getString("EMP_F_name"),
                    rs.getString("EMP_Surname"), rs.getString("EMP_Address"), rs.getString("EMP_Contact"),
                    rs.getString("EMP_Age"), rs.getString("EMP_Gender"), rs.getString("EMP_Department"),
                    rs.getString("EMP_Post"), rs.getString("EMP_Shift"), rs.getString("EMP_H_date"), rs.getString("EMP_B_salary"), rs.getString("EMP_Image")});

            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Close the connection and statement object
                con.close();
                stmt.close();
            } catch (SQLException ex) {
                System.out.println(ex);

            }
        }
    }//GEN-LAST:event_jTexsearchKeyReleased

    private void jTexsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexsearchKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTexsearchKeyPressed

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Employee().setVisible(true);
    }//GEN-LAST:event_jMenu15MouseClicked

    private void jMenuItemAdd_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdd_ActionPerformed
        // TODO add your handling code here:
        this .dispose();
        new Add_employee().setVisible(true);
    }//GEN-LAST:event_jMenuItemAdd_ActionPerformed

    private void jMenuEdit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEdit_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEdit_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_employee().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JEmptable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit_;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemAdd_;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemprint;
    private javax.swing.JMenu jMenulogin;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexsearch;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JMenu jmanulogout;
    private javax.swing.JMenu jmanuprint_;
    // End of variables declaration//GEN-END:variables

}
